[package]
name = "graphql-benchmark"
version = "0.1.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = "2.4.5"
async-std = { version = "1.8.0", features = ["attributes"] }
juniper = "0.15.1"
futures = "0.3.8"
serde_json = "1.0.61"
lazy_static = "1.4.0"
